import { Option, none, some } from "fp-ts/lib/Option"
import { Cell } from "../domain/Cell.ts"

export function cellToString(cell: Cell): Option<string> {
    switch (cell) {
        case Cell.C0:      return some(` `)
        case Cell.C2346:   return some(`!`)
        case Cell.C5:      return some(`"`)
        case Cell.C3456:   return some(`#`)
        case Cell.C1246:   return some(`$`)
        case Cell.C146:    return some(`%`)
        case Cell.C12346:  return some(`&`)
        case Cell.C3:      return some(`'`)
        case Cell.C12356:  return some(`(`)
        case Cell.C23456:  return some(`)`)
        case Cell.C16:     return some(`*`)
        case Cell.C346:    return some(`+`)
        case Cell.C6:      return some(`,`)
        case Cell.C36:     return some(`-`)
        case Cell.C46:     return some(`.`)
        case Cell.C34:     return some(`/`)
        case Cell.C356:    return some(`0`)
        case Cell.C2:      return some(`1`)
        case Cell.C23:     return some(`2`)
        case Cell.C25:     return some(`3`)
        case Cell.C256:    return some(`4`)
        case Cell.C26:     return some(`5`)
        case Cell.C235:    return some(`6`)
        case Cell.C2356:   return some(`7`)
        case Cell.C236:    return some(`8`)
        case Cell.C35:     return some(`9`)
        case Cell.C156:    return some(`:`)
        case Cell.C56:     return some(`;`)
        case Cell.C126:    return some(`<`)
        case Cell.C123456: return some(`=`)
        case Cell.C345:    return some(`>`)
        case Cell.C1456:   return some(`?`)
        case Cell.C4:      return some(`@`)
        case Cell.C1:      return some(`A`)
        case Cell.C12:     return some(`B`)
        case Cell.C14:     return some(`C`)
        case Cell.C145:    return some(`D`)
        case Cell.C15:     return some(`E`)
        case Cell.C124:    return some(`F`)
        case Cell.C1245:   return some(`G`)
        case Cell.C125:    return some(`H`)
        case Cell.C24:     return some(`I`)
        case Cell.C245:    return some(`J`)
        case Cell.C13:     return some(`K`)
        case Cell.C123:    return some(`L`)
        case Cell.C134:    return some(`M`)
        case Cell.C1345:   return some(`N`)
        case Cell.C135:    return some(`O`)
        case Cell.C1234:   return some(`P`)
        case Cell.C12345:  return some(`Q`)
        case Cell.C1235:   return some(`R`)
        case Cell.C234:    return some(`S`)
        case Cell.C2345:   return some(`T`)
        case Cell.C136:    return some(`U`)
        case Cell.C1236:   return some(`V`)
        case Cell.C2456:   return some(`W`)
        case Cell.C1346:   return some(`X`)
        case Cell.C13456:  return some(`Y`)
        case Cell.C1356:   return some(`Z`)
        case Cell.C246:    return some(`[`)
        case Cell.C1256:   return some(`\\`)
        case Cell.C12456:  return some(`]`)
        case Cell.C45:     return some(`^`)
        case Cell.C456:    return some(`_`)
        default:           return none
    }
}